---
environment:
  matrix:
    - RUBY_VERSION: 25-x64
    - RUBY_VERSION: 24-x64

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - set SIMPLECOV=yes
  - gem install bundler -v 2.1.4
  - bundle -v
  - bundle install --retry 2

build: off

branches:
  only:
    - main

before_test:
  - bundle env
  - type Gemfile.lock

test_script:
  - bundle exec rake

# Uncomment this block to enable RDP access to the AppVeyor test instance for
# debugging purposes.
# on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
