name: "ci"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  spec:
    strategy:
      fail-fast: false
      matrix:
        ruby_version:
          - "3.3"
          - "3.2"
          - "3.1"
        puppet_gem_version:
          - '~> 8.0'
        runs_on:
          - "ubuntu-latest"
          - "windows-latest"
        include:
          - ruby_version: '3.1'
            puppet_gem_version: '~> 7.0'
            runs_on: 'ubuntu-latest'
    name: "spec (${{ matrix.runs_on }} ruby ${{ matrix.ruby_version }} | puppet ${{matrix.puppet_gem_version}})"
    uses: "puppetlabs/cat-github-actions/.github/workflows/gem_ci.yml@main"
    secrets: "inherit"
    with:
      rake_task: "spec:coverage"
      ruby_version: ${{ matrix.ruby_version }}
      puppet_gem_version: ${{ matrix.puppet_gem_version }}
      runs_on: ${{ matrix.runs_on }}

  acceptance:
    needs: "spec"
    strategy:
      matrix:
        ruby_version:
          - "3.3"
          - "3.2"
          - "3.1"
        puppet_gem_version:
          - '~> 8.0'
          - 'https://github.com/puppetlabs/puppet'
        runs_on:
          - "ubuntu-latest"
          - "windows-latest"
        include:
          - ruby_version: '3.1'
            puppet_gem_version: '~> 7.0'
            runs_on: 'ubuntu-latest'
    name: "acceptance (${{ matrix.runs_on }} ruby ${{ matrix.ruby_version }} | puppet ${{matrix.puppet_gem_version}})"
    uses: "puppetlabs/cat-github-actions/.github/workflows/gem_acceptance.yml@main"
    secrets: "inherit"
    with:
      ruby_version: ${{ matrix.ruby_version }}
      puppet_version: ${{ matrix.puppet_gem_version }}
      runs_on: ${{ matrix.runs_on }}
